---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: demo-app-ns
automountServiceAccountToken: false

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  namespace: demo-app-ns
spec:
  serviceAccountName: demo-app-sa
  automountServiceAccountToken: false
  containers:
  - name: demo-app-container
    image: ldsingh/demo-app-hello-world:sha256:df286eb78dec2f0cefb684a4592f2a16b15af844785ef68b18f45cef2e50a4f3
    command: ['index.js']
    securityContext:
       privileged: false
       allowPrivilegeEscalation: false
       runAsUser: 65532
       capabilities:
          drop:
            - ALL
